// <auto-generated />
namespace Vidly_Real.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IntialMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191737571_IntialMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
